print(" Mary's cosmetics ")
print('신씨가 소리를 질렀다 "도둑이야"')
print("c:\Windows")
print("\n")
print("안녕\t 만나서 반갑습니다.")
print("오늘은", "일요일")
print("naver; kakao; sk")
print("naver", "kakao", "sk", sep=";")
print("first");print("second")
print("first", end=" ");print("second")
print(5/3)